# /var/lib/kubelet/config.yaml
# https://godoc.org/k8s.io/kubelet/config/v1beta1#KubeletConfiguration

---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: {{ansible_default_ipv4.address}}
kubeletCgroups: /systemd/system.slice
cgroupDriver: systemd
authentication:
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
  anonymous:
    enabled: true
  webhook:
    enabled: true
authorization:
  mode: AlwaysAllow
failSwapOn: false
featureGates:
  DevicePlugins: true
staticPodPath: /etc/kubernetes/manifests
clusterDomain: {{cluster_domain}}
clusterDNS:
  - {{cluster_dns}}
maxPods: 110
