# - name: install calicoctl
#   get_url:
#     url: https://github.com/projectcalico/calicoctl/releases/download/v3.2.8/calicoctl-linux-amd64
#     dest: /usr/bin/calicoctl
#     mode: 0755
#     force: yes
#   tags:
#     - install-calicoctl

- name: create calico directory to store calico yaml
  file:
    path: /usr/local/kube/calico/
    state: directory
    mode: 0755
  tags:
    - calico

- name: render calico yaml
  template:
    newline_sequence: "\n"
    backup: yes
    force: yes
    src: calico.yaml
    dest: /usr/local/kube/calico/calico.yaml
    group: root
    owner: root
    mode: 0640
  when:
    - inventory_hostname == groups['masters'][0]
  tags:
    - calico

- name: kubectl apply calico yaml
  shell: |
    source /etc/profile.d/kube-env.sh
    kubectl apply -f /usr/local/kube/calico/calico.yaml
  when:
    - inventory_hostname == groups['masters'][0]
  tags:
    - calico
