---

# the file list docker images used in gpu cluster
- name: docker pull images
  shell: |
    docker pull {{ item }}
  with_items:
    - "nvidia/k8s-device-plugin:{{ nvidia_device_plugin_version | default('1.11') }}"
  when:
    - ansible_distribution == 'Ubuntu' and has_gpu
  tags:
    - docker
