---

- name: Copy the customed pki-master.cnf
  template:
    newline_sequence: "\n"
    trim_blocks: no
    backup: yes
    force: yes
    src: pki-master.cnf
    dest: /etc/kubernetes/pki/pki-master.cnf
  tags:
    - kube-master
    - kube
    - update_cert

- name: Copy k8s create-master-crt.sh
  copy:
    src: create-master-crt.sh
    dest: /etc/kubernetes/pki/create-master-crt.sh
    mode: 0755
  tags:
    - kube-master
    - kube
    - update_cert

- name: Generate k8s master certificates
  shell: |
    bash /etc/kubernetes/pki/create-master-crt.sh
  tags:
    - kube-master
    - kube
    - update_cert

- name: render kube static pod yaml
  template:
    newline_sequence: "\n"
    trim_blocks: no
    force: yes
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: kube-apiserver.yaml, dest: /etc/kubernetes/manifests/kube-apiserver.yaml }
    - { src: kube-controller-manager.yaml, dest: /etc/kubernetes/manifests/kube-controller-manager.yaml }
    - { src: kube-scheduler.yaml, dest: /etc/kubernetes/manifests/kube-scheduler.yaml }
  tags:
    - kube-master
    - kube
    - kube-upgrade

- include: kube-apiserver-lb.yaml
